language: node_js

sudo: false

node_js:
  - "0.12"
  - "4.2"

# Directories we want to cache between each build
cache:
  apt: true
  directories:
    - 'node_modules'

# Addons we want to set up
addons:

  # System install
  apt:
    sources:
    - 'ubuntu-toolchain-r-test'
    packages:
    - 'gcc-4.8'
    - 'g++-4.8'

# Environment variables we want to set
env:
  - 'CXX=g++-4.8'
