# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.8.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - node-bitly-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
            - fixtures
          key: node-bitly-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Running tests
          command: npm run test

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Building Distribution
          command: npm run build

workflows:
  version: 2
  do_it:
    jobs:
      - install
      - test:
        requires:
          - install
      - build:
        requires:
          - test
